#pragma once


enum class Direction : uint8_t
{
  Up,
  Down,
  Left,
  Right,
};

enum class TileType : uint8_t
{
  Empty,
  Floor,
  Solid_Block,
  Glass_Block,
  Breakable_Block,
  Movable_Block,
  Movable_Block_Sunk,
  Water,
  Ice,
  Breakable_Ice,
  Conveyer_Belt_Up,
  Conveyer_Belt_Down,
  Conveyer_Belt_Left,
  Conveyer_Belt_Right,
  Mirror_Up_Left,
  Mirror_Up_Right,
  Mirror_Down_Left,
  Mirror_Down_Right,
  Mirror_Rotate_Clockwise_Up_Left,
  Mirror_Rotate_Clockwise_Up_Right,
  Mirror_Rotate_Clockwise_Down_Left,
  Mirror_Rotate_Clockwise_Down_Right,
  Mirror_Rotate_Anticlockwise_Up_Left,
  Mirror_Rotate_Anticlockwise_Up_Right,
  Mirror_Rotate_Anticlockwise_Down_Left,
  Mirror_Rotate_Anticlockwise_Down_Right,
  Enemy_Up,
  Enemy_Down,
  Enemy_Left,
  Enemy_Right,
  Broken_Enemy_Up,
  Broken_Enemy_Down,
  Broken_Enemy_Left,
  Broken_Enemy_Right,
  Teleporter_0,
  Teleporter_1,
  Teleporter_2,
  Teleporter_3,
  Teleporter_4,
  Teleporter_5,
  Teleporter_6,
  Teleporter_7,
  Teleporter_8,
  Teleporter_9,
  Teleporter_10,
  Teleporter_11,
  Teleporter_12,
  Teleporter_13,
  Teleporter_14,
  Teleporter_15,
};
